Update Intl.DateTimeFormat to read options only once
Implements https://github.com/tc39/ecma402/pull/709

Introduced test failures:
```sh
$ npm run test:test262 -- --extended-tests --run-slow-tests $(
    find $(
      find test/test262/test262/ -type d -a '(' -iname '*intl*' -o -iname '*402*' ')' -prune | \
      tee /dev/stderr \
    ) -iname '*date*' -prune | \
    grep -viE 'temporal|\bdate\b|\bsupportedValuesOf\b|\bDisplayName'
  ) 2>&1 | \
  grep -vE '^[[:space:]]+ at ' | \
  tee /dev/stderr | \
  awk '/^FAILURE/ { a[$2]++ } END { print "\n\nFILES" > "/dev/stderr"; for(f in a) print f }' | \
  sort -u
test/test262/test262/test/staging/Intl402
test/test262/test262/test/intl402
test/test262/test262/implementation-contributed/v8/intl
test/test262/test262/implementation-contributed/v8/test262/local-tests/test/intl402

> @engine262/engine262@0.0.1 test:test262
> node --enable-source-maps test/test262/test262.js --extended-tests --run-slow-tests test/test262/test262/test/intl402/DateTimeFormat test/test262/test262/test/intl402/Intl/DateTimeFormat test/test262/test262/implementation-contributed/v8/test262/local-tests/test/intl402/DateTimeFormat

 engine262 Test Runner
 Detected 4 CPUs
 Not running on CI

[00:00|:  342|+    0|-    0|»   20] (0.00/s)
FAILURE! intl402/DateTimeFormat/constructor-options-order-dayPeriod.js
Checks the order of getting options of 'dayPeriod' for the DateTimeFormat constructor. (Strict Mode)
Error: Expected [day, dayPeriod, hour] and [day, dayPeriod, hour, day, dayPeriod, hour] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order-dayPeriod.js
Checks the order of getting options of 'dayPeriod' for the DateTimeFormat constructor.
Error: Expected [day, dayPeriod, hour] and [day, dayPeriod, hour, day, dayPeriod, hour] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order-timedate-style.js
Checks the order of getting options for the DateTimeFormat constructor.
Error: Expected [localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher, dateStyle, timeStyle] and [weekday, year, month, day, hour, minute, second, dateStyle, timeStyle, localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher, dateStyle, timeStyle] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js
Checks the order of getting options of 'fractionalSecondDigits' for the DateTimeFormat constructor. (Strict Mode)
Error: Expected [localeMatcher, second, fractionalSecondDigits, timeZoneName, formatMatcher] and [second, fractionalSecondDigits, localeMatcher, second, fractionalSecondDigits, timeZoneName, formatMatcher] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order.js
Checks the order of getting options for the DateTimeFormat constructor. (Strict Mode)
Error: Expected [localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher] and [weekday, year, month, day, hour, minute, second, localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order.js
Checks the order of getting options for the DateTimeFormat constructor.
Error: Expected [localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher] and [weekday, year, month, day, hour, minute, second, localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js
Checks the order of getting options of 'fractionalSecondDigits' for the DateTimeFormat constructor.
Error: Expected [localeMatcher, second, fractionalSecondDigits, timeZoneName, formatMatcher] and [second, fractionalSecondDigits, localeMatcher, second, fractionalSecondDigits, timeZoneName, formatMatcher] to have the same contents.

FAILURE! intl402/DateTimeFormat/constructor-options-order-timedate-style.js
Checks the order of getting options for the DateTimeFormat constructor. (Strict Mode)
Error: Expected [localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher, dateStyle, timeStyle] and [weekday, year, month, day, hour, minute, second, dateStyle, timeStyle, localeMatcher, hour12, hourCycle, timeZone, weekday, era, year, month, day, hour, minute, second, timeZoneName, formatMatcher, dateStyle, timeStyle] to have the same contents.
[00:04|:  342|+  314|-    8|»   20] (70.00/s)

FILES
intl402/DateTimeFormat/constructor-options-order-dayPeriod.js
intl402/DateTimeFormat/constructor-options-order-fractionalSecondDigits.js
intl402/DateTimeFormat/constructor-options-order-timedate-style.js
intl402/DateTimeFormat/constructor-options-order.js
```